# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DBTestApplication' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire-SwiftyJSON'
	pod 'Alamofire' 
	pod 'SwiftyJSON'
	pod 'RealmSwift'
  # Pods for DBTestApplication

  target 'DBTestApplicationTests' do
    inherit! :search_paths
	pod 'Mockit', '1.4.0'
    # Pods for testing
  end

end
